"""Replay the existing v4 quote matcher on immutable single-quote system proposals."""

from copy import deepcopy
from hashlib import sha256

from pydantic import ValidationError

from src.common.io import digest, normalise_space
from src.extraction.adaptive_glyph_grounding import (
    GLYPH_POLICY_V4,
    ground_quote_v4,
    is_substitutable_control,
)
from src.systems.config import SystemConfig
from src.systems.extraction import validate_system_candidate
from src.systems.schema import SystemObservation


def bind_system_job_v4(job: dict) -> dict:
    """Bind unchanged source blocks to v4 under a new, local-only job hash.

    Args:
        job: Original approved system payload, including its input hash.

    Returns:
        A separately hashed validator job with the exact existing v4 policy.
    """
    original = {key: value for key, value in job.items() if key != "input_hash"}
    if digest(original) != job["input_hash"]:
        raise ValueError("original_system_payload_hash_mismatch")
    bound = deepcopy(original)
    bound.update({
        "source_job_input_hash": job["input_hash"],
        "validation_mode": "glyph_v4_on_system_single_quote_v1",
        "glyph_policy": deepcopy(GLYPH_POLICY_V4),
        "glyph_source_hashes": {
            "source_id": job["source_id"],
            "blocks": {
                block["block_id"]: sha256(block["text"].encode("utf-8")).hexdigest()
                for block in job["blocks"]
            },
        },
    })
    bound["input_hash"] = digest(bound)
    return bound


def audit_system_candidate_v4(
    candidate: dict, job: dict, bound: dict, config: SystemConfig, minimum_confidence: float,
) -> tuple[dict | None, dict]:
    """Apply v4 quotation recovery and preserve every other system check.

    Args:
        candidate: Original model proposal with unmodified schema fields.
        job: Original approved system payload.
        bound: Local v4 job generated by ``bind_system_job_v4``.
        config: Existing system configuration.
        minimum_confidence: Frozen extraction-confidence threshold.

    Returns:
        An accepted record with its original identity and raw quote, or None,
        plus separate quotation and complete-validator comparison results.
    """
    if bound != bind_system_job_v4(job):
        raise ValueError("v4_job_binding_mismatch")
    baseline, baseline_reason = validate_system_candidate(candidate, job, config, minimum_confidence)
    audit = {
        "source_id": job["source_id"], "input_hash": job["input_hash"],
        "v4_input_hash": bound["input_hash"], "candidate_hash": digest(candidate),
        "baseline_accepted": baseline is not None, "baseline_reason": baseline_reason,
        "quote_match": None, "quote_reason": None,
        "v4_accepted": False, "v4_reason": baseline_reason,
        "candidate": deepcopy(candidate),
    }
    try:
        original = SystemObservation.model_validate(candidate).model_dump()
    except ValidationError:
        return None, audit
    audit["record_id"] = digest(original)
    blocks = {block["block_id"]: block for block in job["blocks"]}
    block = blocks.get(original["block_id"])
    if original["source_id"] != job["source_id"] or block is None:
        audit["quote_reason"] = "unknown_source_or_block"
        return None, audit
    audit.update(
        declared_section=original["section"], source_section=block["section"],
        section_matches=original["section"] == block["section"],
        target_in_emitted_quote=normalise_space(original["target_name_as_written"])
        in normalise_space(original["evidence_quote"]),
        emitted_control_codepoints=sorted({
            f"U+{ord(character):04X}" for character in original["evidence_quote"]
            if is_substitutable_control(character)
        }),
    )
    match, reason = ground_quote_v4(original["evidence_quote"], block, bound)
    audit.update(quote_match=match, quote_reason=reason)
    if match is None:
        audit["v4_reason"] = reason
        return None, audit
    canonical = {**original, "evidence_quote": match["matched_source_quote"]}
    record, reason = validate_system_candidate(canonical, job, config, minimum_confidence)
    audit.update(v4_accepted=record is not None, v4_reason=reason)
    if record is None:
        return None, audit
    record.update(original)
    record["record_id"] = digest(original)
    record["v4_input_hash"] = bound["input_hash"]
    record["quote_grounding_route"] = match["route"]
    record["grounded_source_quote"] = match
    return record, audit
