"""Render the audited study report from the deterministic content manifest."""

import argparse
import json
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def printable(value: object) -> str:
    """Keep presentation text separate from verbatim source glyphs."""
    return str(value).translate(str.maketrans({"\u2013": "-", "\u2014": "-", "\u2212": "-"}))


def footer(canvas: Canvas, document: SimpleDocTemplate) -> None:
    """Draw a restrained footer and page number."""
    canvas.saveState()
    canvas.setFillColor(colors.HexColor("#52616B"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(42, 24, "SAVERSCHEK 2010 | Text-based behavioural audit | 12 September 2026")
    canvas.drawRightString(A4[0] - 42, 24, str(document.page))
    canvas.restoreState()


def main() -> None:
    """Build a paginated PDF from content generated by the audit builder."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("results/saverschek_audit/report_content.json"))
    parser.add_argument("--output", type=Path, default=Path("output/pdf/saverschek_behavioral_audit.pdf"))
    args = parser.parse_args()
    content = json.loads(args.input.read_text())
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("ReportTitle", fontName="Helvetica-Bold", fontSize=24,
                              leading=28, textColor=colors.HexColor("#133B3A"), spaceAfter=15))
    styles.add(ParagraphStyle("ReportBody", fontName="Helvetica", fontSize=10,
                              leading=14, spaceAfter=9, textColor=colors.HexColor("#23323D")))
    styles.add(ParagraphStyle("ReportLead", parent=styles["ReportBody"], fontSize=12, leading=17,
                              textColor=colors.HexColor("#17675E"), spaceAfter=14))
    styles.add(ParagraphStyle("Cell", fontName="Helvetica", fontSize=8, leading=10))
    styles.add(ParagraphStyle("HeadCell", parent=styles["Cell"], fontName="Helvetica-Bold",
                              textColor=colors.white))
    story = []
    for index, page in enumerate(content["pages"]):
        if index:
            story.append(PageBreak())
        story.append(Paragraph(escape(printable(page["title"])), styles["ReportTitle"]))
        if page.get("lead"):
            story.append(Paragraph(escape(printable(page["lead"])), styles["ReportLead"]))
        for item in page["items"]:
            if item["type"] == "paragraph":
                story.append(Paragraph(escape(printable(item["text"])), styles["ReportBody"]))
            elif item["type"] == "table":
                rows = [[Paragraph(escape(printable(cell)), styles["HeadCell" if i == 0 else "Cell"])
                         for cell in row] for i, row in enumerate([item["headers"], *item["rows"]])]
                table = Table(rows, colWidths=item["widths"], repeatRows=1, hAlign="LEFT")
                table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#17675E")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#EFF5F3"), colors.white]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 7),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.extend([table, Spacer(1, 12)])
            elif item["type"] == "image":
                story.extend([Image(item["path"], width=item["width"], height=item["height"]), Spacer(1, 10)])
            else:
                raise ValueError(f"Unknown report item: {item['type']}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    document = SimpleDocTemplate(str(args.output), pagesize=A4, rightMargin=42, leftMargin=42,
                                 topMargin=42, bottomMargin=42, title=content["title"],
                                 author="Behaviour-Chemistry project / Codex source audit")
    document.build(story, onFirstPage=footer, onLaterPages=footer)
    print(args.output)


if __name__ == "__main__":
    main()
